spring:
  application:
    name: GATEWAY-SERVER
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: CARDS-SERVICE
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/v1/cards/**
          filters:
            - TokenRelay=
        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/oauth2/**    # Match the exact path prefix for OAuth2 endpoints
          filters:
            - TokenRelay=        # Relays the token from request if available
            - RewritePath=/oauth2/(?<segment>.*), /oauth2/$\{segment}   # Forward full path without changes if needed
      default-filters:
        - TokenRelay
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#            allowedHeaders:
#              - Authorization
#              - Content-Type
#              - Cache-Control
#            allowCredentials: true
#            maxAge: 3600
  security:
    oauth2:
      client:
        provider:
          mobile:
            issuer-uri: http://localhost:8080
        registration:
          mobile:
            client-id: mobile
            client-secret: password
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: http://127.0.0.1:3000/api/auth/callback

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security: DEBUG